#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("nfcAndroid.Resource", IsApplication=true)]

namespace nfcAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040014
			public const int assegnaTrasfusione = 2130968596;
			
			// aapt resource value: 0x7f040004
			public const int btnUpdateSacca = 2130968580;
			
			// aapt resource value: 0x7f040007
			public const int btnregistraSacca = 2130968583;
			
			// aapt resource value: 0x7f040005
			public const int buttonLogin = 2130968581;
			
			// aapt resource value: 0x7f04000a
			public const int cognomePaziente = 2130968586;
			
			// aapt resource value: 0x7f040001
			public const int editGruppoSacca = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int editRhSacca = 2130968578;
			
			// aapt resource value: 0x7f040008
			public const int gridLayout1 = 2130968584;
			
			// aapt resource value: 0x7f04000b
			public const int gruppoPaziente = 2130968587;
			
			// aapt resource value: 0x7f04000f
			public const int gruppoSacca = 2130968591;
			
			// aapt resource value: 0x7f040009
			public const int nomePaziente = 2130968585;
			
			// aapt resource value: 0x7f04000c
			public const int rhPaziente = 2130968588;
			
			// aapt resource value: 0x7f040010
			public const int rhSacca = 2130968592;
			
			// aapt resource value: 0x7f04000d
			public const int startScanPaziente = 2130968589;
			
			// aapt resource value: 0x7f040012
			public const int startScanSacca = 2130968594;
			
			// aapt resource value: 0x7f040011
			public const int statoSaccaTrasfusione = 2130968593;
			
			// aapt resource value: 0x7f04000e
			public const int stopScanPaziente = 2130968590;
			
			// aapt resource value: 0x7f040013
			public const int stopScanSacca = 2130968595;
			
			// aapt resource value: 0x7f040003
			public const int textStato = 2130968579;
			
			// aapt resource value: 0x7f040006
			public const int uidSaccaRegistrazione = 2130968582;
			
			// aapt resource value: 0x7f040000
			public const int uidSaccaUpdate = 2130968576;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public const int AggiornaSacca = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Main = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int RegistrazioneSacca = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Trasfusione = 2130837507;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030000
			public const int app_name = 2130903040;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
